-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2020-12-01 20:53:54 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012

drop table "address";
drop table "complaint";
drop table "user_account";
drop table "question";
drop table "goods";
drop table "solution";
drop table "order";
drop table "customer";
drop table "employee";



CREATE TABLE Address 
    (
     address_id INTEGER IDENTITY (1, 1) NOT NULL , 
     city CHAR (40) NOT NULL , 
     street CHAR (40) NOT NULL , 
     number INTEGER NOT NULL , 
     postal_number INTEGER , 
     customer_customer_id INTEGER , 
     employee_employee_id INTEGER 
    )
GO 

    

ALTER TABLE Address ADD CONSTRAINT Address_PK PRIMARY KEY CLUSTERED (address_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE complaint 
    (
     complaint_id INTEGER IDENTITY (1, 1) NOT NULL , 
     start_date DATE NOT NULL , 
     end_date DATE , 
     reason VARCHAR (max) NOT NULL , 
     order_order_id INTEGER NOT NULL , 
     employee_employee_id INTEGER NOT NULL , 
     result VARCHAR (max) 
    )
GO

ALTER TABLE complaint ADD CONSTRAINT complaint_PK PRIMARY KEY CLUSTERED (complaint_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE customer 
    (
     first_name CHAR (15) NOT NULL , 
     customer_id INTEGER IDENTITY (1, 1) NOT NULL , 
     last_name CHAR (25) NOT NULL , 
     phone_number INTEGER NOT NULL 
    )
GO

ALTER TABLE customer ADD CONSTRAINT Customer_PK PRIMARY KEY CLUSTERED (customer_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE employee 
    (
     employee_id INTEGER IDENTITY (1, 1) NOT NULL , 
     first_name CHAR (15) NOT NULL , 
     last_name CHAR (25) NOT NULL , 
     phone_number INTEGER NOT NULL , 
     rank CHAR (15) NOT NULL 
    )
GO

ALTER TABLE employee ADD CONSTRAINT employee_PK PRIMARY KEY CLUSTERED (employee_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE goods 
    (
     goods_id INTEGER IDENTITY (1, 1) NOT NULL , 
     price FLOAT NOT NULL , 
     type CHAR (50) NOT NULL , 
     solution_solution_id INTEGER NOT NULL 
    )
GO

ALTER TABLE goods ADD CONSTRAINT goods_PK PRIMARY KEY CLUSTERED (goods_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE "order" 
    (
     order_id INTEGER IDENTITY (1, 1) NOT NULL , 
     state CHAR (20) NOT NULL , 
     start_date DATETIME NOT NULL , 
     end_date DATETIME , 
     description VARCHAR (max) NOT NULL , 
     computer_type CHAR (2) NOT NULL , 
     customer_customer_id INTEGER NOT NULL , 
     employee_employee_id INTEGER NOT NULL , 
     employee_technician_id INTEGER NOT NULL 
    )
GO

ALTER TABLE "order" ADD CONSTRAINT order_PK PRIMARY KEY CLUSTERED (order_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE question 
    (
     question_id INTEGER IDENTITY (1, 1) NOT NULL , 
     date DATE NOT NULL , 
     description VARCHAR (max) NOT NULL , 
     type CHAR (10) NOT NULL , 
     customer_customer_id INTEGER NOT NULL , 
     employee_employee_id INTEGER NOT NULL 
    )
GO

ALTER TABLE question ADD CONSTRAINT question_PK PRIMARY KEY CLUSTERED (question_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE solution 
    (
     solution_id INTEGER IDENTITY (1, 1) NOT NULL , 
     date DATE NOT NULL , 
     description VARCHAR (max) NOT NULL , 
     order_order_id INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    solution__IDX ON solution 
    ( 
     order_order_id 
    ) 
GO

ALTER TABLE solution ADD CONSTRAINT solution_PK PRIMARY KEY CLUSTERED (solution_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE user_account 
    (
     user_id INTEGER IDENTITY (1, 1) NOT NULL , 
     user_name CHAR (20) NOT NULL , 
     password CHAR (20) NOT NULL , 
     customer_customer_id INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    user_account__IDX ON user_account 
    ( 
     customer_customer_id 
    ) 
GO

ALTER TABLE user_account ADD CONSTRAINT user_account_PK PRIMARY KEY CLUSTERED (user_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Address 
    ADD CONSTRAINT Address_customer_FK FOREIGN KEY 
    ( 
     customer_customer_id
    ) 
    REFERENCES customer 
    ( 
     customer_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Address 
    ADD CONSTRAINT Address_employee_FK FOREIGN KEY 
    ( 
     employee_employee_id
    ) 
    REFERENCES employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE complaint 
    ADD CONSTRAINT complaint_employee_FK FOREIGN KEY 
    ( 
     employee_employee_id
    ) 
    REFERENCES employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE complaint 
    ADD CONSTRAINT complaint_order_FK FOREIGN KEY 
    ( 
     order_order_id
    ) 
    REFERENCES "order" 
    ( 
     order_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE goods 
    ADD CONSTRAINT goods_solution_FK FOREIGN KEY 
    ( 
     solution_solution_id
    ) 
    REFERENCES solution 
    ( 
     solution_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE "order" 
    ADD CONSTRAINT order_customer_FK FOREIGN KEY 
    ( 
     customer_customer_id
    ) 
    REFERENCES customer 
    ( 
     customer_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE "order" 
    ADD CONSTRAINT order_employee_FK FOREIGN KEY 
    ( 
     employee_employee_id
    ) 
    REFERENCES employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE "order" 
    ADD CONSTRAINT order_employee_FKv1 FOREIGN KEY 
    ( 
     employee_technician_id
    ) 
    REFERENCES employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE question 
    ADD CONSTRAINT question_customer_FK FOREIGN KEY 
    ( 
     customer_customer_id
    ) 
    REFERENCES customer 
    ( 
     customer_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE question 
    ADD CONSTRAINT question_employee_FK FOREIGN KEY 
    ( 
     employee_employee_id
    ) 
    REFERENCES employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE solution 
    ADD CONSTRAINT solution_order_FK FOREIGN KEY 
    ( 
     order_order_id
    ) 
    REFERENCES "order" 
    ( 
     order_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE user_account 
    ADD CONSTRAINT user_account_customer_FK FOREIGN KEY 
    ( 
     customer_customer_id
    ) 
    REFERENCES customer 
    ( 
     customer_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             3
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
